AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04e601abe3e1a910f
      InstanceType: t2.micro
      KeyName: terraform-key
      SecurityGroups:
        - !Ref msgroup
      UserData:
        Fn::Base64: !Sub |
           #!/bin/bash -xe
            apt update -y
            sudo apt install unzip
            apt install -y docker.io docker-compose
            usermod -aG docker $USER
            usermod -aG docker ubuntu
            sudo mkdir new_project 
            sudo touch docker-compose.yml
           
  msgroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for SSH and HTTP access"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
